# Generated by Django 5.0.1 on 2024-01-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hotelbooking_hotel_alter_hotelimages_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='booking_tyoe',
            new_name='booking_type',
        ),
    ]
